[profile.default]
solc_version = "0.8.28"
evm_version = "paris" # prevent use of PUSH0 opcode until it is widely supported
optimizer = true
via_ir = true
extra_output = ["asm", "metadata", "storageLayout", "evm.deployedBytecode.immutableReferences"]

libs = [
    "lib",
]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "wormhole-sdk/=lib/wormhole-solidity-sdk/src/",
    "core-bridge/=src/",
]
