[profile.default]
solc_version = "0.8.28"
evm_version = "paris" # prevent use of PUSH0 opcode until it is widely supported
optimizer = true
optimizer_runs = 100000
via_ir = true
extra_output = ["evm.assembly", "irOptimized", "metadata", "storageLayout", "evm.deployedBytecode.immutableReferences"]

libs = [
    "lib",
]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "wormhole-sdk/=lib/wormhole-solidity-sdk/src/",
    "core-bridge/=src/",
]

[fuzz]
runs = 10000
# seed = "0x3e1"
dictionary_weight = 60
max_test_rejects = 6553600