[package]
name = "wormhole-contract"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true, features = ["alloc"] }
stellar-strkey = "0.0.14"
wormhole-interface = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
base64 = "0.21"
serde_json = "1.0"
hex = "0.4"
