# Unstable options are commented out below. We should re-enable them once they are stabilized.

# Merge similar crates together to avoid multiple use statements.
# imports_granularity = "Crate"

# Consistency in formatting makes tool based searching/editing better.
# empty_item_single_line = false

# Easier editing when arbitrary mixed use statements do not collapse.
# imports_layout = "Vertical"

# Default rustfmt formatting of match arms with branches is awful.
match_arm_leading_pipes = "Preserve"
