[package]
name    = "wormhole-sdk"
version = "0.1.0"
edition = "2018"


[features]
# Helper methods will target the Wormhole mainnet contract addresses.
mainnet   = []

# Helper methosd will target the Wormhole devnet contract addresses.
devnet    = []

# Enable Optional dependencies that are only required when targetting Terra.
terra = [
  "cosmwasm-std",
  "cosmwasm-storage",
  "schemars",
  "serde",
  "wormhole-bridge-terra",
]

# Enable Optional dependencies that are only required when targetting Solana.
solana = [
  "solana-program",
  "wormhole-bridge-solana",
]

[profile.release]
opt-level = 3
lto       = "thin"

[dependencies]
borsh           = { version="0.8.1" }
nom             = { version="7", default-features=false, features=["alloc"] }
primitive-types = { version = "0.9.0", default-features = false }
wormhole-core   = { path="../core", version="0.1.0" }

# Solana Specific
solana-program = { version="1.7.0", optional=true }

# Terra Specific
cosmwasm-std     = { version = "0.16.0", optional=true }
cosmwasm-storage = { version = "0.16.0", optional=true }
schemars         = { version = "0.8.1", optional=true }
serde            = { version = "1.0.103", default-features = false, features = ["derive"], optional=true }

[dependencies.wormhole-bridge-solana]
path     = "../../../solana/bridge/program"
version  = "0.1.0"
optional = true
features = [ "no-entrypoint" ]

[dependencies.wormhole-bridge-terra]
path     = "../../../terra/contracts/wormhole"
version  = "0.1.0"
optional = true


[dev-dependencies]
byteorder      = "*"
hex            = "*"
