[package]
name = 'Deployer'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'alin/move-keccak'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
deployer="0x5ad53ef0cb7cd21816a0371c367be38e7874a9d2f71c77af7592f6b0791f6ca3"