[package]
name = 'Deployer'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = '6f83bc6d02207298b2dee91133d75538789bf582'
subdir = 'aptos-move/framework/aptos-framework'

[dev-addresses]
deployer="0x277fa055b6a73c42c0662d5236c65c864ccbf2d4abd21f174a30c8b786eab84b"

[addresses]
deployer="_"
