[package]
name    = "wormhole-messenger-terra"
version = "0.0.1"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library    = []
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
borsh                     = "=0.8.1"
cosmwasm-std              = { version = "0.16.0" }
cosmwasm-storage          = { version = "0.16.0" }
schemars                  = "0.8.1"
serde                     = { version = "1.0.103", default-features = false, features = ["derive"] }
wormhole-sdk              = { path = "../../../sdk/rust/sdk", features = ["devnet", "terra"] }
wormhole-messenger-common = { path = "../common" }

[dev-dependencies]
cosmwasm-vm = { version = "0.16.0", default-features = false }
serde_json  = "1.0"
