[package]
name = "Coins"
version = "0.1.0"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "4e759d9b48"

[dependencies.Wormhole]
local = "../../wormhole"

[dependencies.TokenBridge]
local = "../../token_bridge"

[addresses]
coins = "_"

[dev-dependencies.Wormhole]
local = "../../wormhole"

[dev-dependencies.TokenBridge]
local = "../../token_bridge"

[dev-addresses]
wormhole = "0x100"
token_bridge = "0x200"
coins = "0x20c"
