[package]
name = "wormhole-verify-vaa-shim"
description = "Created with Anchor"
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = [ "from-env" ]
no-entrypoint = []

### Network types
testnet = ["wormhole-svm-definitions/testnet"]
localnet = ["wormhole-svm-definitions/localnet"]

### Specific networks
solana = ["wormhole-svm-definitions/solana"]

from-env = ["wormhole-svm-definitions/from-env"]

[dependencies]
solana-program.workspace = true
wormhole-svm-definitions.workspace = true
wormhole-svm-shim.workspace = true

[dev-dependencies]
base64.workspace = true
borsh.workspace = true
solana-program-test.workspace = true
solana-sdk.workspace = true
wormhole-svm-definitions = { workspace = true, features = ["borsh"]}
