[package]
name = "wormhole-core-bridge-solana"
description = "Wormhole Core Bridge Program for Solana"
version = "0.0.1-alpha.2"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["mainnet", "cpi", "no-idl"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
### A.K.A. Local Validator (via JS Integration Test) and Tilt
localnet = []
### A.K.A. Solana Mainnet-Beta
mainnet = []
### A.K.A. Solana Devnet
testnet = []

[dependencies]
wormhole-io.workspace = true
wormhole-raw-vaas.workspace = true

anchor-lang.workspace = true
solana-program.workspace = true

hex.workspace = true
ruint.workspace = true

cfg-if.workspace = true
