[package]
name = "client"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.40"
borsh = "=0.9.1"
token-bridge = { path = "../program", features = ["client"] }
clap = "2.33.0"
rand = "0.7.3"
shellexpand = "2.1.0"
solana-client = "=1.9.4"
solana-program = "=1.9.4"
solana-sdk = "=1.9.4"
solana-cli-config = "=1.9.4"
solitaire = { path = "../../../solitaire/program" }
solitaire-client = { path = "../../../solitaire/client" }
solana-clap-utils = "=1.9.4"
hex = "0.4.3"
spl-token-metadata = { path = "../token-metadata" }