[package]
name = "verification_v2"
version = "0.1.0"
description = "Wormhole threshold signature verification program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "verification_v2"

[features]
default = ["mainnet"]
mainnet = ["wormhole-anchor-sdk/mainnet"]
testnet = ["wormhole-anchor-sdk/solana-devnet"]
devnet = ["wormhole-anchor-sdk/tilt-devnet"]
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = [
	"anchor-lang/idl-build",
	"wormhole-anchor-sdk/idl-build",
]

[dependencies]
anchor-lang = "0.31.1"
byteorder = "1.5.0"
libsecp256k1 = "0.7.2"
primitive-types = "0.13.1"
# wormhole-anchor-sdk = { git = "https://github.com/wormhole-foundation/wormhole-scaffolding.git", default-features = false }
wormhole-anchor-sdk = { git = "https://github.com/XLabs/wormhole-scaffolding.git", rev = "3811c6c4beadbf2f1fc42ce038bfea925a596872", default-features = false }

[dev-dependencies]
num-bigint = "0.4"
num-traits = "0.2"